### ISSUE TITLE
Providing Type without Version fails

### ISSUE THREAD

**Issue by myspivey** [nfantone/gulp-release#13]
If providing type of release without specifying version tag causes release to fail.

$ gulp release -t patch
[11:22:34] Using gulpfile ~/gulpfile.js
[11:22:34] Starting 'release'...
[11:22:34] Starting 'release:start'...
[11:22:34] git flow release start -F 1.0.2
Switched to a new branch 'release/1.0.2'

Summary of actions:
- A new branch 'release/1.0.2' was created, based on 'develop'
- You are now on branch 'release/1.0.2'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '1.0.2'

[11:22:35] Finished 'release:start' after 1.23 s
[11:22:35] Starting 'bump'...
[11:22:35] Bumped 1.0.2 to 1.0.3 with type: patch
[11:22:35] Codename is "Platinum Uninorth"
[11:22:35] Finished 'bump' after 44 ms
[11:22:35] Starting 'release:commit'...
[11:22:35] Finished 'release:commit' after 30 ms
[11:22:35] Starting 'release:finish'...
[11:22:35] git flow release finish -m 'Platinum Uninorth' 1.0.3
Fatal: Branch 'release/1.0.3' does not exist and is required.
[11:22:35] 'release:finish' errored after 602 ms
[11:22:35] Error: Command `git flow release finish -m 'Platinum Uninorth' 1.0.3` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[11:22:35] [gulp-release] All done: review changes and push to origin
[11:22:35] Finished 'release' after 1.91 s

**Comment by nfantone** [comment]
Thanks. Will check this out right away.

**Comment by nfantone** [comment]
@myspivey Ok, this is gonna have to wait a while, since it seems like [an issue over at gulp-bump](https://github.com/stevelacy/gulp-bump/issues/55).

Would you mind +1ing it?

**Comment by nfantone** [comment]
Ok, issue is resolved. 

Incidentally, https://github.com/nfantone/gulp-release/pull/14/commits/c4657ba4ab13b66dbf72d7e62dfd8767948fa289 on #14 fixes this, as well.

**Comment by myspivey** [comment]
Working on PR #14.

**Comment by nfantone** [comment]
Fixed on `1.1.0` (https://www.npmjs.com/package/gulp-release)
